### ISSUE TITLE
Export settings

### ISSUE THREAD

**Issue by Ypot** [lujun9972/org-eww#21]
Could it be possible to use the "html export settings" when generating the preview?

**Comment by jakebox** [comment]
What kind of options are you looking for? I think that's doable.

**Comment by Ypot** [comment]
Hi!
Any option? ;D
For example a CSS?

My setting:
#+SETUPFILE: ~\export\theme-readtheorg.setup

#+LANGUAGE: es
#+options: \n:t
#+options:   toc:2
#+options: broken-links:mark

Where _theme-readtheorg.setup_ could be:
```
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/readtheorg.css"/>

#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://fniessen.github.io/org-html-themes/src/lib/js/jquery.stickytableheaders.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/js/readtheorg.js"></script>
```

**Comment by jakebox** [comment]
Oh. Well in that case, you can just put that into your Org file. Have you tried that? It works. That is how I use it. I thought you meant the options offered in `org-export-dispatch`.

**Comment by Ypot** [comment]
OH!
You are right. I wasn't getting it because I was using narrowed trees.
Thanks!!
